name: "Bookshelf Action: New Issue"
on:
  issues:
    types: [opened]
jobs:
  bookshelf-action:
    name: Bookshelf Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Run Bookshelf Action
        uses: AnandChowdhary/bookshelf-action@HEAD
        with:
          command: "onNewIssue"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Delay for 10 seconds
        if: github.repository =='alexdeathway/books'
        run: sleep 10
      
